export enum VACANCIES_ACTION_TYPES {
  SET_CURRENT_VACANCIES = 'SET_CURRENT_VACANCIES',
  SET_FILTERED_VACANCIES = 'SET_FILTERED_VACANCIES',
  FETCH_VACANCIES_START = 'FETCH_VACANCIES_START',
  FETCH_VACANCIES_SUCCESS = 'FETCH_VACANCIES_SUCCESS',
  FETCH_VACANCIES_FAILED = 'FETCH_VACANCIES_FAILED',
}
